# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\DroneControlDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(340, 272)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.right_btn = QtWidgets.QPushButton(Dialog)
        self.right_btn.setObjectName("right_btn")
        self.horizontalLayout.addWidget(self.right_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.connect_button = QtWidgets.QPushButton(Dialog)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout.addWidget(self.connect_button)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_3.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "<-"))
        self.right_btn.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.right_btn.setText(_translate("Dialog", "->"))
        self.connect_button.setText(_translate("Dialog", "Connect"))
