# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(905, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.main_video = QtWidgets.QWidget(self.splitter)
        self.main_video.setObjectName("main_video")
        self.result_area = QtWidgets.QWidget(self.splitter)
        self.result_area.setObjectName("result_area")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_choose_video_file = QtWidgets.QAction(MainWindow)
        self.action_choose_video_file.setObjectName("action_choose_video_file")
        self.action_load_analysis = QtWidgets.QAction(MainWindow)
        self.action_load_analysis.setObjectName("action_load_analysis")
        self.menuFile.addAction(self.action_choose_video_file)
        self.menuFile.addAction(self.action_load_analysis)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FLYJUMP"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_choose_video_file.setText(_translate("MainWindow", "Open Video"))
        self.action_choose_video_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_load_analysis.setText(_translate("MainWindow", "Load Analysis"))
        self.action_load_analysis.setShortcut(_translate("MainWindow", "Ctrl+L"))
