# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(749, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.main_video = QtWidgets.QWidget(self.splitter)
        self.main_video.setObjectName("main_video")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_analysis_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.start_analysis_btn.setObjectName("start_analysis_btn")
        self.horizontalLayout.addWidget(self.start_analysis_btn)
        self.filter_combo = QtWidgets.QComboBox(self.layoutWidget)
        self.filter_combo.setObjectName("filter_combo")
        self.horizontalLayout.addWidget(self.filter_combo)
        self.filtered_out_checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.filtered_out_checkBox.setObjectName("filtered_out_checkBox")
        self.horizontalLayout.addWidget(self.filtered_out_checkBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.video_loaded_label = QtWidgets.QLabel(self.layoutWidget)
        self.video_loaded_label.setObjectName("video_loaded_label")
        self.verticalLayout.addWidget(self.video_loaded_label)
        self.result_area = QtWidgets.QWidget(self.splitter_2)
        self.result_area.setMinimumSize(QtCore.QSize(300, 0))
        self.result_area.setObjectName("result_area")
        self.horizontalLayout_2.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 749, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDrone = QtWidgets.QMenu(self.menubar)
        self.menuDrone.setObjectName("menuDrone")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_choose_video_file = QtWidgets.QAction(MainWindow)
        self.action_choose_video_file.setObjectName("action_choose_video_file")
        self.action_load_analysis = QtWidgets.QAction(MainWindow)
        self.action_load_analysis.setObjectName("action_load_analysis")
        self.action_control_drone = QtWidgets.QAction(MainWindow)
        self.action_control_drone.setObjectName("action_control_drone")
        self.menuFile.addAction(self.action_choose_video_file)
        self.menuFile.addAction(self.action_load_analysis)
        self.menuDrone.addAction(self.action_control_drone)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDrone.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FLYJUMP"))
        self.start_analysis_btn.setText(_translate("MainWindow", "Analyze"))
        self.filtered_out_checkBox.setText(_translate("MainWindow", "save filtered video"))
        self.video_loaded_label.setText(_translate("MainWindow", "loaded video:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDrone.setTitle(_translate("MainWindow", "Drone"))
        self.action_choose_video_file.setText(_translate("MainWindow", "Open Video"))
        self.action_choose_video_file.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_load_analysis.setText(_translate("MainWindow", "Load Analysis"))
        self.action_load_analysis.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action_control_drone.setText(_translate("MainWindow", "Control"))
